require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/recipees', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Recipee. As you add validations to Recipee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Recipee.create! valid_attributes
      get recipees_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      recipee = Recipee.create! valid_attributes
      get recipee_url(recipee)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_recipee_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      recipee = Recipee.create! valid_attributes
      get edit_recipee_url(recipee)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Recipee' do
        expect do
          post recipees_url, params: { recipee: valid_attributes }
        end.to change(Recipee, :count).by(1)
      end

      it 'redirects to the created recipee' do
        post recipees_url, params: { recipee: valid_attributes }
        expect(response).to redirect_to(recipee_url(Recipee.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Recipee' do
        expect do
          post recipees_url, params: { recipee: invalid_attributes }
        end.to change(Recipee, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post recipees_url, params: { recipee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested recipee' do
        recipee = Recipee.create! valid_attributes
        patch recipee_url(recipee), params: { recipee: new_attributes }
        recipee.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the recipee' do
        recipee = Recipee.create! valid_attributes
        patch recipee_url(recipee), params: { recipee: new_attributes }
        recipee.reload
        expect(response).to redirect_to(recipee_url(recipee))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        recipee = Recipee.create! valid_attributes
        patch recipee_url(recipee), params: { recipee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested recipee' do
      recipee = Recipee.create! valid_attributes
      expect do
        delete recipee_url(recipee)
      end.to change(Recipee, :count).by(-1)
    end

    it 'redirects to the recipees list' do
      recipee = Recipee.create! valid_attributes
      delete recipee_url(recipee)
      expect(response).to redirect_to(recipees_url)
    end
  end
end
